// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               v5.29.3
// source: order.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { Empty } from "./google/protobuf/empty.pb";

export const protobufPackage = "order";

export enum OrderStatus {
  DEFAULT = 0,
  PROCESSING = 1,
  COMPLETED = 2,
  CANCELLED = 3,
  PENDING = 4,
  UNRECOGNIZED = -1,
}

export interface OrderData {
  id: string;
  productId: string;
  productName: string;
  productPrice: number;
  quantity: number;
  totalAmount: number;
  userId: string;
  status: OrderStatus;
}

export interface CreateRequest {
  productId: string;
  quantity: number;
  userId: string;
}

/** FindOne */
export interface FindOneRequest {
  id: string;
}

export interface FindOneResponse {
  order: OrderData | undefined;
}

/** FindMany */
export interface FindManyRequest {
  userId: string;
  status: OrderStatus;
}

export interface FindManyResponse {
  orders: OrderData[];
}

export const ORDER_PACKAGE_NAME = "order";

export interface OrderServiceClient {
  createOrder(request: CreateRequest): Observable<Empty>;

  findOne(request: FindOneRequest): Observable<FindOneResponse>;

  findMany(request: FindManyRequest): Observable<FindManyResponse>;
}

export interface OrderServiceController {
  createOrder(request: CreateRequest): void;

  findOne(request: FindOneRequest): Promise<FindOneResponse> | Observable<FindOneResponse> | FindOneResponse;

  findMany(request: FindManyRequest): Promise<FindManyResponse> | Observable<FindManyResponse> | FindManyResponse;
}

export function OrderServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["createOrder", "findOne", "findMany"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("OrderService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("OrderService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const ORDER_SERVICE_NAME = "OrderService";
